# Generated by Django 4.2.28 on 2026-03-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneHerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb_id', models.CharField(max_length=50, verbose_name='中药ID')),
                ('herb_name', models.CharField(max_length=100, verbose_name='中药名称')),
                ('herb_cn_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名称')),
                ('gene', models.CharField(max_length=50, verbose_name='关联基因')),
                ('pubmed_id', models.FloatField(blank=True, null=True, verbose_name='PubMed ID')),
                ('reference_title', models.TextField(blank=True, null=True, verbose_name='文献标题')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='关系类型')),
                ('p_value', models.FloatField(blank=True, null=True, verbose_name='P值')),
            ],
            options={
                'verbose_name': '基因中药关联',
                'verbose_name_plural': '基因中药关联数据',
            },
        ),
    ]
